import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a professional, user-customized PDF Report for SCADA/BMS Platform
 * @param {Object} options
 */
export function generateUserCustomPdfReport({
  title = 'SCADA BMS Custom Operational Report',
  subtitle = 'System Telemetry & Performance Audit',
  siteName = 'Main Site',
  userName = 'Rajesh Padhi',
  userRole = 'Super Admin',
  dateRange = 'Last 7 Days (Aug 10 - Aug 17, 2026)',
  kpis = [],
  headers = [],
  data = [],
  notes = '',
  fileName = 'BMS_Custom_Report.pdf'
}) {
  try {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // 1. Header Banner (Dark Navy #0f172a)
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 28, 'F');

    // Title in Header
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(15);
    doc.setFont('helvetica', 'bold');
    doc.text(String(title).toUpperCase(), 14, 12);

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(`${subtitle}  |  iSmartAccess BMS Platform`, 14, 19);

    // Metadata Box (Right Side of Header)
    doc.setFontSize(8);
    doc.setTextColor(203, 213, 225);
    doc.text(`Generated By: ${userName} (${userRole})`, pageWidth - 14, 10, { align: 'right' });
    doc.text(`Target Site: ${siteName}`, pageWidth - 14, 16, { align: 'right' });
    doc.text(`Date: ${new Date().toLocaleString('en-IN')}`, pageWidth - 14, 22, { align: 'right' });

    let currentY = 34;

    // 2. Filter & Date Range Banner
    doc.setFillColor(241, 245, 249); // Slate 100
    doc.rect(14, currentY, pageWidth - 28, 11, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.rect(14, currentY, pageWidth - 28, 11, 'S');

    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(`Report Period: `, 18, currentY + 7);
    doc.setFont('helvetica', 'normal');
    doc.text(String(dateRange), 42, currentY + 7);

    doc.setFont('helvetica', 'bold');
    doc.text(`Scope / Site: `, pageWidth - 70, currentY + 7);
    doc.setFont('helvetica', 'normal');
    doc.text(String(siteName), pageWidth - 48, currentY + 7);

    currentY += 16;

    // 3. KPI Summary Cards Section (if provided)
    if (Array.isArray(kpis) && kpis.length > 0) {
      doc.setFontSize(10.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('Key Performance Indicators (Summary)', 14, currentY);
      currentY += 4;

      const cardWidth = (pageWidth - 28 - (kpis.length - 1) * 3) / kpis.length;
      kpis.forEach((kpi, idx) => {
        const xPos = 14 + idx * (cardWidth + 3);
        doc.setFillColor(248, 250, 252);
        doc.rect(xPos, currentY, cardWidth, 16, 'F');
        doc.setDrawColor(203, 213, 225);
        doc.rect(xPos, currentY, cardWidth, 16, 'S');

        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 116, 139);
        doc.text(String(kpi.label || ''), xPos + 3, currentY + 5);

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text(`${kpi.value || ''} ${kpi.unit || ''}`, xPos + 3, currentY + 12);
      });

      currentY += 21;
    }

    // 4. Data Table Section
    if (Array.isArray(headers) && headers.length > 0 && Array.isArray(data) && data.length > 0) {
      autoTable(doc, {
        startY: currentY,
        head: [headers],
        body: data,
        theme: 'grid',
        headStyles: {
          fillColor: [15, 23, 42],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 8.5,
          halign: 'left'
        },
        bodyStyles: {
          fontSize: 8,
          textColor: [51, 65, 85],
          cellPadding: 2.5
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252]
        },
        margin: { left: 14, right: 14 },
        didDrawPage: (dataArg) => {
          const totalPages = doc.internal.getNumberOfPages();
          const pageNum = doc.internal.getCurrentPageInfo().pageNumber;

          // Page Footer
          doc.setFillColor(15, 23, 42);
          doc.rect(0, pageHeight - 10, pageWidth, 10, 'F');

          doc.setFontSize(7.5);
          doc.setTextColor(148, 163, 184);
          doc.setFont('helvetica', 'normal');
          doc.text('CONFIDENTIAL - iSmartAccess SCADA BMS Platform Operational Report', 14, pageHeight - 4);
          doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 14, pageHeight - 4, { align: 'right' });
        }
      });

      currentY = doc.lastAutoTable.finalY + 8;
    }

    // 5. Custom User Notes / Observations
    if (notes && String(notes).trim() !== '') {
      if (currentY + 22 > pageHeight - 15) {
        doc.addPage();
        currentY = 20;
      }

      doc.setFillColor(254, 252, 232); // Light yellow #fefce8
      doc.rect(14, currentY, pageWidth - 28, 18, 'F');
      doc.setDrawColor(253, 224, 71);
      doc.rect(14, currentY, pageWidth - 28, 18, 'S');

      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(161, 98, 7);
      doc.text('User Remarks & Operational Notes:', 18, currentY + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(113, 63, 18);
      const splitNotes = doc.splitTextToSize(String(notes), pageWidth - 36);
      doc.text(splitNotes, 18, currentY + 11);
    }

    // Save the PDF document!
    doc.save(fileName);
    return true;
  } catch (err) {
    console.error('PDF Generation error:', err);
    alert('Failed to generate PDF: ' + err.message);
    return false;
  }
}
