import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Sanitizes strings for PDF rendering to avoid font encoding bugs (e.g. ₹ rupee symbol, unicode dashes)
 */
function sanitizePdfText(val) {
  if (val === null || val === undefined) return '';
  return String(val)
    .replace(/₹\s?/g, 'INR ')
    .replace(/[^\x00-\x7F]/g, (char) => {
      if (char === '•') return '-';
      if (char === '’' || char === '‘') return "'";
      if (char === '“' || char === '”') return '"';
      if (char === '–' || char === '—') return '-';
      if (char === '°') return ' deg ';
      if (char === 'φ') return 'phi';
      return '';
    })
    .trim();
}

/**
 * Generates an executive, publication-grade PDF Report for SCADA/BMS Platform
 * Designed to eliminate text collisions, prevent card overflowing, and format currency/units cleanly.
 * @param {Object} options
 */
export function generateUserCustomPdfReport({
  title = 'Energy Billing & Consumption Report',
  subtitle = 'System Telemetry & Performance Audit',
  siteName = 'Testing Site',
  targetMeter = '',
  refId = '',
  userName = localStorage.getItem('userName') || 'Operator',
  userRole = localStorage.getItem('userRole') || 'Engineer',
  dateRange = 'Last 7 Days',
  kpis = [],
  headers = [],
  data = [],
  notes = '',
  fileName = 'Energy_Report.pdf'
}) {
  try {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();   // 210 mm
    const pageHeight = doc.internal.pageSize.getHeight(); // 297 mm
    const margin = 14;
    const printableWidth = pageWidth - margin * 2;        // 182 mm

    // ==========================================
    // 1. EXECUTIVE HEADER BANNER (Navy #0f172a)
    // ==========================================
    const headerHeight = 32;
    doc.setFillColor(15, 23, 42); // Slate-900 / Deep Navy
    doc.rect(0, 0, pageWidth, headerHeight, 'F');

    // Accent line at bottom of header banner (Cyan #0ea5e9)
    doc.setFillColor(14, 165, 233);
    doc.rect(0, headerHeight - 1.2, pageWidth, 1.2, 'F');

    // Left Column: Brand & Title (Constrained to max width 110mm to prevent any collision)
    const leftColWidth = 110;
    
    // Top tiny category pill text
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(56, 189, 248); // Sky-400
    doc.text('ISMARTACCESS BMS PLATFORM  •  AUDIT REPORT', margin, 8.5);

    // Primary Title - Auto sized and wrapped
    const cleanTitle = sanitizePdfText(title).toUpperCase();
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    const titleFontSize = cleanTitle.length > 35 ? 11.5 : 13;
    doc.setFontSize(titleFontSize);
    const splitTitle = doc.splitTextToSize(cleanTitle, leftColWidth);
    doc.text(splitTitle, margin, 14.5);

    // Subtitle below title
    const titleLines = Array.isArray(splitTitle) ? splitTitle.length : 1;
    const subtitleY = 14.5 + titleLines * (titleFontSize * 0.38) + 2;
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate-400
    const cleanSub = sanitizePdfText(subtitle);
    const splitSub = doc.splitTextToSize(cleanSub, leftColWidth);
    doc.text(splitSub, margin, subtitleY);

    // Right Column: Metadata Box (Right-aligned at pageWidth - margin)
    const rightMargin = pageWidth - margin;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text(`Site: ${sanitizePdfText(siteName)}`, rightMargin, 9, { align: 'right' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(203, 213, 225); // Slate-300
    if (refId) {
      doc.text(`Ref ID: ${sanitizePdfText(refId)}`, rightMargin, 14.5, { align: 'right' });
    }
    doc.text(`Generated By: ${sanitizePdfText(userName)} (${sanitizePdfText(userRole)})`, rightMargin, 20, { align: 'right' });
    
    const nowStr = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
    doc.setTextColor(148, 163, 184);
    doc.text(`Timestamp: ${nowStr}`, rightMargin, 25.5, { align: 'right' });

    let currentY = headerHeight + 5;

    // ==========================================
    // 2. PARAMETERS & SCOPE STRIP
    // ==========================================
    const stripHeight = 11;
    doc.setFillColor(241, 245, 249); // Slate-100
    doc.roundedRect(margin, currentY, printableWidth, stripHeight, 1.5, 1.5, 'F');
    doc.setDrawColor(203, 213, 225); // Slate-300
    doc.roundedRect(margin, currentY, printableWidth, stripHeight, 1.5, 1.5, 'S');

    doc.setFontSize(8);
    // Item 1: Report Period
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Period:', margin + 4, currentY + 7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(sanitizePdfText(dateRange), margin + 17, currentY + 7);

    // Item 2: Target Facility / Site
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Facility:', margin + 68, currentY + 7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(sanitizePdfText(siteName), margin + 82, currentY + 7);

    // Item 3: Target Meter Node (if passed)
    if (targetMeter) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text('Target Node:', margin + 124, currentY + 7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      const cleanMeter = sanitizePdfText(targetMeter);
      const truncatedMeter = cleanMeter.length > 20 ? cleanMeter.substring(0, 19) + '...' : cleanMeter;
      doc.text(truncatedMeter, margin + 144, currentY + 7);
    }

    currentY += stripHeight + 6;

    // ==========================================
    // 3. KPI SUMMARY METRIC CARDS
    // ==========================================
    if (Array.isArray(kpis) && kpis.length > 0) {
      doc.setFontSize(9.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('Key Performance Indicators (Summary)', margin, currentY);
      currentY += 4;

      // Smart Grid layout: up to 4 cards per row to give ample space
      const itemsPerRow = kpis.length > 4 ? 3 : Math.min(kpis.length, 4);
      const cardGap = 3.5;
      const cardWidth = (printableWidth - (itemsPerRow - 1) * cardGap) / itemsPerRow;
      const cardHeight = 17;

      kpis.forEach((kpi, idx) => {
        const col = idx % itemsPerRow;
        const row = Math.floor(idx / itemsPerRow);
        const cardX = margin + col * (cardWidth + cardGap);
        const cardY = currentY + row * (cardHeight + cardGap);

        // Card background
        doc.setFillColor(248, 250, 252); // Slate-50
        doc.roundedRect(cardX, cardY, cardWidth, cardHeight, 1.2, 1.2, 'F');
        doc.setDrawColor(226, 232, 240); // Slate-200
        doc.roundedRect(cardX, cardY, cardWidth, cardHeight, 1.2, 1.2, 'S');

        // Left accent bar
        doc.setFillColor(14, 165, 233); // Sky-500
        doc.rect(cardX, cardY, 1.4, cardHeight, 'F');

        // Card Label (uppercase small)
        doc.setFontSize(6.8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(100, 116, 139); // Slate-500
        const cleanLabel = sanitizePdfText(kpi.label || '').toUpperCase();
        doc.text(cleanLabel, cardX + 4, cardY + 5.5);

        // Card Value (bold, auto-scaling to never overflow)
        const rawVal = `${kpi.value ?? ''}${kpi.unit ? ' ' + kpi.unit : ''}`;
        const cleanVal = sanitizePdfText(rawVal);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42); // Slate-900

        // Calculate dynamic font size to guarantee fit within cardWidth - 7mm
        const maxTextWidth = cardWidth - 7;
        let valFontSize = 10.5;
        doc.setFontSize(valFontSize);
        let measuredWidth = doc.getTextWidth(cleanVal);
        if (measuredWidth > maxTextWidth) {
          valFontSize = Math.max(7, Math.floor(valFontSize * (maxTextWidth / measuredWidth)));
          doc.setFontSize(valFontSize);
        }

        doc.text(cleanVal, cardX + 4, cardY + 12.5);
      });

      const totalRows = Math.ceil(kpis.length / itemsPerRow);
      currentY += totalRows * (cardHeight + cardGap) + 4;
    }

    // ==========================================
    // 4. DATA TABLE SECTION (autoTable)
    // ==========================================
    if (Array.isArray(headers) && headers.length > 0 && Array.isArray(data) && data.length > 0) {
      // Clean headers & row data to prevent broken glyphs like ₹
      const sanitizedHeaders = headers.map(h => sanitizePdfText(h));
      const sanitizedData = data.map(row => {
        if (!Array.isArray(row)) return [];
        return row.map(cell => sanitizePdfText(cell));
      });

      // Build column alignment mapping based on column headers
      const columnStylesConfig = {};
      sanitizedHeaders.forEach((h, colIdx) => {
        const lowerH = h.toLowerCase();
        if (
          lowerH.includes('consumption') ||
          lowerH.includes('cost') ||
          lowerH.includes('demand') ||
          lowerH.includes('load') ||
          lowerH.includes('tariff') ||
          lowerH.includes('kwh') ||
          lowerH.includes('kw')
        ) {
          columnStylesConfig[colIdx] = { halign: 'right', fontStyle: 'bold' };
        } else if (
          lowerH.includes('pf') ||
          lowerH.includes('factor') ||
          lowerH.includes('status') ||
          lowerH.includes('date')
        ) {
          columnStylesConfig[colIdx] = { halign: 'center' };
        } else if (colIdx === 0) {
          columnStylesConfig[colIdx] = { fontStyle: 'bold' };
        }
      });

      autoTable(doc, {
        startY: currentY,
        head: [sanitizedHeaders],
        body: sanitizedData,
        theme: 'grid',
        headStyles: {
          fillColor: [15, 23, 42],     // Deep Navy
          textColor: [255, 255, 255],  // White
          fontStyle: 'bold',
          fontSize: 8,
          cellPadding: 3.2,
          valign: 'middle'
        },
        bodyStyles: {
          fontSize: 7.5,
          textColor: [30, 41, 59],     // Slate-800
          cellPadding: 2.8,
          lineColor: [226, 232, 240],  // Slate-200
          lineWidth: 0.2,
          valign: 'middle'
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252]   // Slate-50
        },
        columnStyles: columnStylesConfig,
        margin: { left: margin, right: margin },
        didDrawPage: () => {
          const totalPages = doc.internal.getNumberOfPages();
          const pageNum = doc.internal.getCurrentPageInfo().pageNumber;

          // Executive Page Footer
          const footerH = 9;
          const footerY = pageHeight - footerH;
          doc.setFillColor(15, 23, 42); // Navy
          doc.rect(0, footerY, pageWidth, footerH, 'F');

          doc.setFontSize(7);
          doc.setTextColor(148, 163, 184); // Slate-400
          doc.setFont('helvetica', 'normal');
          doc.text('CONFIDENTIAL  |  iSmartAccess SCADA BMS Platform  |  Official Audit Copy', margin, footerY + 5.5);
          doc.text(`Page ${pageNum} of ${totalPages}`, rightMargin, footerY + 5.5, { align: 'right' });
        }
      });

      currentY = doc.lastAutoTable.finalY + 8;
    }

    // ==========================================
    // 5. USER NOTES / REMARKS (if provided)
    // ==========================================
    if (notes && String(notes).trim() !== '') {
      if (currentY + 24 > pageHeight - 15) {
        doc.addPage();
        currentY = 20;
      }

      const noteBoxHeight = 18;
      doc.setFillColor(254, 252, 232); // Light amber #fefce8
      doc.roundedRect(margin, currentY, printableWidth, noteBoxHeight, 1.2, 1.2, 'F');
      doc.setDrawColor(253, 224, 71); // Amber border #fde047
      doc.roundedRect(margin, currentY, printableWidth, noteBoxHeight, 1.2, 1.2, 'S');

      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(161, 98, 7); // Amber-800
      doc.text('Operational Notes & Remarks:', margin + 4, currentY + 5.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(113, 63, 18);
      const splitNotes = doc.splitTextToSize(sanitizePdfText(notes), printableWidth - 8);
      doc.text(splitNotes, margin + 4, currentY + 11);
    }

    // Save PDF
    doc.save(fileName);
    return true;
  } catch (err) {
    console.error('PDF Generation error:', err);
    alert('Failed to generate PDF: ' + err.message);
    return false;
  }
}
